### ISSUE TITLE
Unhandled /jobs 404 error

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/google-bigquery-writer#29]
Teď to naházelo pár errorů na https://github.com/keboola/google-bigquery-writer/blob/c070853f7e1ba70b97de733a26dc63cc661f28ed/google_bigquery_writer/writer.py#L119

Nevím, jak to zreprodukovat

```
File "/usr/local/lib/python3.6/site-packages/google/cloud/bigquery/client.py", line 845, in load_table_from_file
file_obj, job_resource, num_retries)
File "/usr/local/lib/python3.6/site-packages/google/cloud/bigquery/client.py", line 930, in _do_resumable_upload
response = upload.transmit_next_chunk(transport)
File "/usr/local/lib/python3.6/site-packages/google/resumable_media/requests/upload.py", line 396, in transmit_next_chunk
self._process_response(result, len(payload))
File "/usr/local/lib/python3.6/site-packages/google/resumable_media/_upload.py", line 574, in _process_response
self._get_status_code, callback=self._make_invalid)
File "/usr/local/lib/python3.6/site-packages/google/resumable_media/_helpers.py", line 93, in require_status_code
status_code, u'Expected one of', *status_codes)
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 404, 'Expected one of', <HTTPStatus.OK: 200>, 308)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "./main.py", line 11, in main
application.run()
File "/home/google_bigquery_writer/app.py", line 63, in run
self.action_run()
File "/home/google_bigquery_writer/app.py", line 118, in action_run
incremental=incremental
File "/home/google_bigquery_writer/writer.py", line 140, in write_table_sync
incremental=incremental
File "/home/google_bigquery_writer/writer.py", line 122, in write_table
job_config=job_config
File "/usr/local/lib/python3.6/site-packages/google/cloud/bigquery/client.py", line 850, in load_table_from_file
raise exceptions.from_http_response(exc.response)
google.api_core.exceptions.NotFound: 404 PUT https://www.googleapis.com/upload/bigquery/v2/projects/***/jobs?uploadType=resumable&upload_id=***: Not Found
```

Vypadá to, jako by nebyl dostupný endpoint jobů a nebo nebylo nalezeno `uploadId`?

**Comment by padak** [comment]
@ondrejhlavacek já vím! Dělá to tenhle job: https://connection.eu-central-1.keboola.com/admin/projects/80/writers/keboola.wr-google-bigquery/7229294/rows/7229478 Klidně tam vlez a spusť si ho!

**Comment by ondrejhlavacek** [comment]
@padak dělá jich to víc

**Comment by ondrejhlavacek** [comment]
@padak a je to nestabilní, někdy to projde a někdy ne, takže bych to tipl na něco v Googlu, nechal bych to chvíli bejt, jestli se to nespraví, ok?

**Comment by padak** [comment]
OK!
