### ISSUE TITLE
Invalid dataset ID (data-set)

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/google-bigquery-writer#31]
```
message: 147946154733.dkr.ecr.us-east-1.amazonaws.com/developer-portal-v2/keboola.wr-google-bigquery:1.1.0 container '472033663-472033664-472032853-0-keboola-wr-google-bigquery' failed: (3) 400 POST https://www.googleapis.com/bigquery/v2/projects/taste-reporting-226013/datasets" target="_blank">https://www.googleapis.com/bigquery/v2/projects/project/datasets: Invalid dataset ID "data-set". Dataset IDs must be alphanumeric (plus underscores) and must be at most 1024 characters long.
Traceback (most recent call last):
  File "/home/google_bigquery_writer/writer.py", line 15, in obtain_dataset
    return self.bigquery_client.get_dataset(dataset_reference)
  File "/usr/local/lib/python3.6/site-packages/google/cloud/bigquery/client.py", line 332, in get_dataset
    path=dataset_ref.path)
  File "/usr/local/lib/python3.6/site-packages/google/cloud/bigquery/client.py", line 315, in _call_api
    return call()
  File "/usr/local/lib/python3.6/site-packages/google/api_core/retry.py", line 260, in retry_wrapped_func
    on_error=on_error,
  File "/usr/local/lib/python3.6/site-packages/google/api_core/retry.py", line 177, in retry_target
    return target()
  File "/usr/local/lib/python3.6/site-packages/google/cloud/_http.py", line 293, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 GET https://www.googleapis.com/bigquery/v2/projects/project/datasets/data-set: Not found: Dataset project:data-set
```

https://connection.keboola.com/admin/utils/logs?file=2018/12/19/14/2018-12-19-14-56-20-5c1a4e0491f72-exception
https://connection.keboola.com/admin/utils/logs?file=2018/12/19/14/2018-12-19-14-56-20-5c1a4e049e258-log

**Comment by ondrejhlavacek** [comment]
Zas, `Invalid dataset ID "analytics_123456.day_interval"`

https://connection.eu-central-1.keboola.com/admin/utils/logs?file=2019/01/18/15/2019-01-18-15-35-15-5c41e4230ecc5-exception

https://connection.eu-central-1.keboola.com/admin/utils/logs?file=2019/01/18/15/2019-01-18-15-35-15-5c41e42319a41-log

**Comment by ondrejhlavacek** [comment]
a zas, https://keboola.slack.com/archives/C09U3R1J4/p1553499607031700
